language: scala
scala:
  - 2.10.6
  - 2.11.8

script:
  - echo "Scala version:" $TRAVIS_SCALA_VERSION
  - sbt ++$TRAVIS_SCALA_VERSION coverage test coverageReport &&
    sbt coverageAggregate
  - sbt ++$TRAVIS_SCALA_VERSION assembly
